(define ninstruments 4)
(define (geninstruments count)
  (if (zero? count)
    '()
    (append (list (+ 35 (random-integer 46)))
            (geninstruments (- count 1)))))
(define instruments (geninstruments ninstruments))
(write instruments) (newline)
(define (drumline)
  (define beats 4)
  (define (beat)
    (ni (/ ppf beats)
        9
        (list-ref instruments (from0mars->absint 4))))
  (cons-generated beat beats))

(define (bassline)
  (define beats 1)
  (define notes 8)
  (define (beat n)
    (ni (/ ppf (* beats notes))
        2
        n))
  (define (nbeat n)
    (multiply (list (beat n))
              beats))
  (generate-list (lambda() (nbeat (+ 36 (vector-ref scale (random-integer (vector-length scale))))))
                 notes))
